### ISSUE TITLE
Direct download of Munster bar image is 403 forbidden

### ISSUE THREAD

**Issue by cclauss** [ChamGeeks/HackathonPythonista2015#2]
The Munster bar image loads fine in a browser but...

``` python
#!/usr/bin/env python
import requests
image_url = 'http://www.irishpubsglobal.com/wp-content/uploads/2015/10/Munster-Bar5.jpeg'
print(requests.get(image_url).content)
```

**prints:**

```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by cclauss** [comment]
@spathon , @njpearman  Do the other implementations cache the bar images locally or do they always download the images in a WebView each time they are displayed?  The Munster bar image is the only one that exhibits this problem.  All other images work as expected.

**Comment by spathon** [comment]
Don't think anyone go that far so they started to think of caching images and it's been loading without problem for me.
